### PR TITLE
Add missing migration 0005

### PR DESCRIPTION
**Pull request by kutenai**
I am running the beta version since I need Django 2.1 support.
I found that I had to create this migration, so I want ahead and forked it, and submitting the PR.
It would be nice to get this into the mainline soon.

### CODE REVIEW

**Comment by kutenai** [comment]
Wow... All checks faile? I just added a migration.
The tests passed locally, but I did not try all of the different python versions, just running 3.7
will have to look into this more. 
If anyone can point out what I did wrong... I'd appreciate that also.

**Comment by kutenai** [comment]
This does fail locally with the same issue. It looks like this fails on master also.

**Comment by kutenai** [comment]
It looks like this was merged in, or just done locally, so this PR isn't needed anymore.

**Comment by kutenai** [comment]
It looks like this was merged in, or just done locally, so this PR isn't needed anymore.

**Comment by kutenai** [comment]
Oh, never mind.. I just realized this has NOT been merged, it's just that my local version has it. This does need to be merged into the main and released since the current branch isn't usable without the migration.

The checked might pass now due to time zone?? will see

**Comment by dokterbob** [comment]
Superseded by #282 (now in master).

**Pull request closed without merging**
