### PR TITLE
Add possibility to add Attachments to a Message

### PR DESCRIPTION
**Pull request by frennkie**
This PR adds a new `Attachment` model which has a `ForeignKey` to `Message`. With this it is (optionally) possible to upload one or more files for a `Message`. When the message is send out the files are attached as normal e-mail attachments. The "read online" pages include a download link to these files.

A new migration has been created `0006_attachment.py ` and the `graph_models` for the documentation have been updated.

Basic tests for the new functionality are included.

This is a replacement for #145.

Screenshot - Django Admin:
message_admin

Screenshot - Thunderbird:
Thunderbird

Screenshot - Online View:
ReadOnline

### CODE REVIEW

**Comment by frennkie** [comment]
@dokterbob @claudep any suggestion how this could be improved? Or would this be acceptable for merging?

**Comment by frennkie** [comment]
@dokterbob would be great to get any kind of response..! :-D

**Comment by frennkie** [comment]
@dokterbob could you look into this please?

**Comment by dokterbob** [comment]
Sorry for the late reply. I like the idea, especially considering that it's an optional feature. 

Code looks very nice. Coverage *increased*. Very well done! Thanks!

**Pull request merged**
