### PR TITLE
Fix compatibility with Django 2.0

### LINKED ISSUE #239: Fix Django 2.0b1 built errors / Django 2.0 support
Tests are being run for the Django 2.0 beta but yields some error. It would be great to have them fixed. :)

Example of failure:
https://travis-ci.org/dokterbob/django-newsletter/jobs/300566705

Django 2.0 backwards incompatible changes:
https://docs.djangoproject.com/en/dev/releases/2.0/#backwards-incompatible-changes-in-2-0

### PR DESCRIPTION
**Pull request by claudep**
Fixes #239.

### CODE REVIEW

**Comment by claudep** [comment]
Still WIP work.

**Comment by claudep** [comment]
Tests look good now.

**Comment by dokterbob** [comment]
Wonderful work @claudep! Thanks!

Will look at it again some time soon, but so far it looks really great. :)

**Comment by dokterbob** [comment]
@claudep Have you, by any chance, have been able to manually check/eye the admin?

**Comment by claudep** [comment]
No, I haven't.

**Comment by dokterbob** [comment]
Ok. 

I’ll see if I can find a minute (unless someone else beats me to it, again). ;)

**Pull request merged**
