### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by gabn88**
Fix migration 0004

### CODE REVIEW

**Comment by dokterbob** [comment]
Thanks!

Are you absolutely sure this patch does not affect the functionality?

**Comment by gabn88** [comment]
I’m positive. Only place get_default* is used is in the admin form for importing addresses, and that form is still working.

**Comment by dokterbob** [comment]
You double checked that the default is properly set?  :)

**Comment by gabn88** [comment]
The first newsletter was selected for me, so either it works fine or  Django auto selects the first one (which equals the default), so should be good to go :)

**Pull request merged**
