### PR TITLE
Move Pillow to requirements

### LINKED ISSUE #202: Pillow not installed
When running ``./manage.py migrate`` command, ``SystemCheckError`` is provided due to ``Pillow`` not being installed.

### PR DESCRIPTION
**Pull request by cfc603**
Fixes #202

### CODE REVIEW

**Comment by sergei-maertens** [comment]
Highly unlikely, but what if someone has PIL installed instead of Pillow? That would duplicate the dependency, since Django only requires one of both iirc.

**Comment by cfc603** [comment]
@sergei-maertens any suggestions on addressing that scenario?

**Comment by sergei-maertens** [comment]
I think a mention in the installation documentation should suffice - that's how Django itself does it. I just checked - from Django 1.8+ they only support Pillow and no longer PIL. That matches the Django versions supported by newsletter, so my comment is no longer valid.

**Comment by claudep** [comment]
I think that PIL is mostly unmaintained, so encouraging PIllow is fine, IMHO.

**Comment by dokterbob** [comment]
Let's follow the Django support practices and go for Pillow, yeah. :) 

Claude Paroz <notifications@github.com> schreef op 21 april 2016 12:50:15 GMT+01:00:

**Pull request merged**
