### PR TITLE
Isolated the send_message process

### PR DESCRIPTION
**Pull request by claudep**
I have a special and temporary use case where I'll have to send some submission by batches (using a custom script). @dokterbob, would that separation of sending the message in its own method acceptable for you?

### CODE REVIEW

**Comment by dokterbob** [comment]
I'm not sure yet. It costs us a few SLOC's and I'm not sure whether or not it adds clarity.
Perhaps there is a cleaner, better way that stands out as an evident improvement (though I'm not able to come up with it). I'll review it in a few days, perhaps something comes to mind.

**Comment by claudep** [comment]
SLOC vs MacCabe complexity :-)

**Comment by dokterbob** [comment]
Point taken next code day I'll review it again and probably merge it. 

Claude Paroz <notifications@github.com> schreef op 8 februari 2016 13:19:01 CET:

**Comment by dokterbob** [comment]
I've read through it again and I don't think I like it enough to want to maintain it. ;)

The main reason for it is added complexity/reduced clarity. Whereas `send_message()` does not take any other varying paramters than subscription, in its current incantation it requires `templates, current_site, extra_headers` to come along with it. 

While this makes sense from a performance point of view and makes total sense if it were a single function, it does not make much sense as a public API. In this case, because all the other parameters depend on the `Submission` instance.

Hence, I'd be up for merging this type of functionality if the send loop looks like:
            for subscription in subscriptions:
                self.send_message(subscription)

This would yield a bunch of redundant function calls which would indeed make the code slower, which I don't like but in practise is probably not so much of an issue. However, we might figure out a way of caching (i.e.[cached properties](https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.functional.cached_property)) the templates, extra headers and current_site. As a bonus we could use these same helper functions to render previews from the admin.

Question here is: will it break, in practise, because the cache becomes invalid (i.e. newsletter templates or slug change during the lifetime of a subscription instance which is submitting) in a way that yields unexpected behaviour?

**Comment by claudep** [comment]
Like so?

**Comment by claudep** [comment]
BTW, I don't think that caching those content during a Submission instance lifetime is an issue (as long as we are caching on the instance and not on the class).

**Comment by dokterbob** [comment]
Exactly! Well almost. 

Though I think we could cache the templates on the message instance, which is already cached by Django anyways. This way we could use the same property from within the [admin preview](https://github.com/dokterbob/django-newsletter/blob/master/newsletter/admin.py#L259).

Also, I don't think we need to cache the current site as this is typically handled very fast by Django already.

Let me know how you feel about this. I would also accept merging this in as it is.

**Comment by claudep** [comment]
To be reviewed again...

**Comment by dokterbob** [comment]
Nice, perfect. Looking at the code, I think we might make it more explicit by not having the templates in a particular order and having to rely on them but to either make the different templates different properties (i.e. `Message.html_template`) or return a dictionary for explicit lookups. My preference would go to the former (separate properties).

However, I do appreciate your effort on this so far tremendously and the current solution is in no way half-baked. If you're done coding for now I would be happy if you merged as-is to and we'll leave this last change as a nice-to-have-for later. Anyways, it's up to you.

Should you decide for this last change, just make sure the tests pass and you can merge right away (without additional review).

Thanks again!

**Comment by claudep** [comment]
I don't mind going through several review cycles, if things are improving in each version!

**Pull request merged**
