### PR TITLE
Remove legacy Selenium tests.

### PR DESCRIPTION
**Pull request by dokterbob**
Now that there's coverage for essential admin stuff I think it would be good to remove the Selenium tests as they have been totally unmaintained and unused for years and have lots of side effects and take lots of time to run anyways.

Or: it was a good idea *at the time*.

### CODE REVIEW

**Comment by claudep** [comment]
There are clearly things that are not really testable with standard tests. Django also allows using Selenium with its LiveServerTestCase class (https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.LiveServerTestCase). However, this would still mean rewriting all those tests, so I think that's fine to remove them for now.

**Comment by dokterbob** [comment]
Rewriting them has been my plan for several years now - I’m pretty sure I’m not going to do this.

**Comment by claudep** [comment]
We'll rewrite them if and when the need arises.

**Comment by dokterbob** [comment]
In that case I'd like to remove just the tests as they are implemented, starting with the admin tests you recently added. Actually, the only thing where I think they're needed is the interaction with JS code. For the rest I tend to trust Django's integrity.

**Pull request merged**
