### PR TITLE
Fixed addresses serialization with JSON-based sessions

### LINKED ISSUE #104: Subscription object is not JSON serializable
Since Django 1.6 the default session serializer uses JSON objects instead of pickle objects to circumvent potential security issues. However, the import mechanism of django-newsletter stores subscription objects which are not JSON-serializable.

## Exception
http://monosnap.com/image/OWikyTx9p7xURpTwhLNEt86M5rAnYK.png
And traceback gist: https://gist.github.com/amureki/9613750

Error rising after I choose newsletter and CSV from above and press "Upload".

## Workaround
This is due to the change in Django 1.6 session_serializer. Look here https://docs.djangoproject.com/en/1.6/ref/settings/#session-serializer 
So, if you have Django > 1.6 and django-newsletter current version, simplest way — you should add into your settings file:

    SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

## Solution
The solution would be to rewrite the import mechanism to store just the raw imported data in the session and create the subcription objects right before saving. Pull requests are much welcomed!

### PR DESCRIPTION
**Pull request by claudep**
Fixes #104.

### CODE REVIEW

**Comment by dokterbob** [comment]
Thanks for the contrib. I like how your patch is small.

However, it only addresses the issue in the case of CSV and it still serializes the whole `Subscription` object - which might cause further problems in the future.

The solution proposed in #104 is to store the form output rather than the `Subscription` in the session - hence a fully JSON serializable `addresses` dict. This would both solve the problem as well as simplify the code.

Regardless of this, your test is immensely valuable, adding coverage for a coverage-wise delapitated area.

Let me know if you feel like implementing the suggested alternative solution (i.e. storing a dict of addresses in the session and calling `make_subscription()` only in the confirm step) - or if you have any specific reasons why you think this is a bad idea.

Note: in order to simplify the aforementioned work I'll attempt to clean out the relevant areas of the import code a bit, so you might want to run a `git rebase master` before pushing an updated patch.

**Comment by claudep** [comment]
At some time, I wondered if we shouldn't simply rely on django-formtools preview functionality. The drawback of the formtools approach would be that the file would be parsed twice: once for checking the file validity while cleaning the form, and the second time after import confirmation.

I generally don't like storing two much data in sessions, but it may just be my feeling without real reasons.

**Comment by claudep** [comment]
Here we are with an updated patch.

**Comment by claudep** [comment]
I'm about to add a test for the ldif import...

**Comment by claudep** [comment]
ldif and vcard are also tested now.

**Comment by dokterbob** [comment]
Great, thanks so much - especially for the tests (perhaps the most work...)

There is a little bit of feedback on your code, main point is that perhaps a dict would simplify matters over a set and a list and that - if I read it well - duplicates could still end up in the `address` list and generate errors on saving.

I have made one suggestion for a small tool to generalize address processing and uniqueness checking, let me know whether you think it makes sense. Be aware though that it was freehand coding and is likely some way from perfect.

Lastly, I am not entirely sure about the validation of the data (i.e. email addresses) - but I think your patch didn't touch that at all. Anyways, I have been reading into this code today and I figured that abusing the `Address` model's `validate()` method might in fact be an elegant way to assure that we can in fact save this stuff without having separate `check_*()` functions as we do now. You have to know that this stuff was written long before model validation was around. Perhaps this validation could be included in the `add()` function of the suggested `AddressList`.

In any case, I appreciate your contribution very much. It's always better to work together. :)

**Comment by dokterbob** [comment]
@claudep By the way, if you want I could take your work and then finish it from there.

**Comment by dokterbob** [comment]
@claudep Two things:

1. You're officially a collaborator now. You can directly access waffle.io and work on branches rather than your own fork.
2. If you're okay with it I'd like to take your work and update it as per my own comments last night, just so we can be done with it.

**Comment by dokterbob** [comment]
Superseded by #163.

**Comment by claudep** [comment]
Thanks for making me a collaborator. I cannot promise to help in the longer term, as I'm still evaluating the use of django-newsletter in one of my projects. But if the decision is finally positive, count on me!
As for the methodology, I'd still like to work in my fork for small feature branches which are not significant for the global module history. I may commit directly for smaller trivial things.
Hope you don't mind.

**Comment by dokterbob** [comment]
That all sounds fine with me! :)

You can commit your being a contributor in CONTRIBUTORS.txt, if you like, directly. ;)

**Pull request closed without merging**
