### PR TITLE
enconding sender and recipient name as ascii in django<1.9

### PR DESCRIPTION
**Pull request by newearthmartin**
This is a fix for django<1.9, which has a problem sending emails with non ascii names. I previously submitted the same pull request but tests were not passing, now they are.

### CODE REVIEW

**Comment by dokterbob** [comment]
Cool! Thanks for the contrib!

It seems the email notification slipped my attention.

Your patch looks fine, although it would be great to have a comment describing the issue and that this is a workaround, so we can safely remove it when Django 1.8 phases out. 

Other than that it looks fine to me. Maybe add a trailing newline to the file. ^^

**Comment by newearthmartin** [comment]
ok making a new pull request

**Comment by dokterbob** [comment]
No need, you can just keep pushing to the same branch and the PR will automatically update!

**Comment by dokterbob** [comment]
Thanks!

**Comment by newearthmartin** [comment]
ok I added the comment and the newline! Not sure if the comment is in alignment with other comments in your code. Would really appreciate if you can make a release for pip so I can take this from my git submodules

**Comment by dokterbob** [comment]
Hey,

Good idea. I’ll put it on my todo list. Maybe later this week. Do poke me if I forget. ;)

M

**Comment by newearthmartin** [comment]
thanks!! be well!!

**Comment by newearthmartin** [comment]
hello Dr. just a friendly poke for the release :D

**Comment by dokterbob** [comment]
Just was reminded of this bug opened by yourself. It might be nice to fix this for the next release, as it’s probably relatively easy to fix.

https://github.com/dokterbob/django-newsletter/issues/224

What do you think?

**Comment by dokterbob** [comment]
No but I'd prefer to do all at the same time. You don't want to mess up a release, it takes time and attention, so I prefer to include as much as possible. 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by newearthmartin** [comment]
I'm traveling in India for three weeks so I won't be able to look at it until I return

**Comment by dokterbob** [comment]
I wish you a most interesting time there! :)

**Comment by newearthmartin** [comment]
sooooo
I found the bug! can you make the release 😬 🤣

**Comment by dokterbob** [comment]
Hey, hope you had a good holiday. As you might notice, I already released. This issue has been merged!

**Comment by newearthmartin** [comment]
oh great! 
did you check the thread about the other bug? why do you think those lines are there?

**Pull request merged**
