### PR TITLE
Fixed Python 3 syntax and API issues

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by gabn88** [comment]
I have tested it and seems to work, however after creating a newsletter, subscription and a message and clicking on 2016 I got the following error:

ValueError at /admin/newsletter/message/
Database returned an invalid value in QuerySet.datetimes(). Are time zone definitions for your database and pytz installed?

I have pytz installed. Don't know what you mean by time zone definitions, but I have my timezone set in the settings.

**Comment by claudep** [comment]
I expect some more fixes to come, because coverage is currently a bit low. I have some code locally to improve test coverage, but let's wait for the current patch backlog to be merged before exploring that further.
You might then open a new ticket for your issue.

**Comment by dokterbob** [comment]
@gabn88 Could you confirm whether or not your issue occurs on the master branch? It sounds unlikely to be a related issue to me, considering the changes in this PR. Perhaps you're using a database without timezone support but have `USE_TZ` enabled?

As `test_web.ArchiveTestcase.test_archive_timezone_regression` explicitly tests the timezone support, I doubt that this issue is related. However, I do hate to commit broken code to master so I'll leave it open for feedback for a day or so and otherwise just merge.

**Comment by gabn88** [comment]
@dokterbob 
You are right, I have a DB without TZ support and I have USE_TZ enabled. However, this is not a misconfiguration! It just says that django needs to be aware that all my dates and times in the database are according to the timezone that I specified in the settings!

Not related to this PR though! Will make another issue.

**Comment by dokterbob** [comment]
@gabn88 Ok, thanks for the quick feedback.

**Comment by gabn88** [comment]
Just for the reference, the issue only showed on my development server, because I indeed forgot to set the mysql_tzinfo. mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p fixed it!

**Pull request merged**
