### PR TITLE
fix issue 221 ('Dear None' when name field is empty)

### PR DESCRIPTION
**Pull request by manikos**

### CODE REVIEW

**Comment by dokterbob** [comment]
Thanks! 

As we are pulling in translated strings from Transifex all at once before releases, do you think you could update the pull request to only include source strings (the English `.po` file)? Keeps the history a bit cleaner. I'll happily submit it to Transifex straight after so translators can do their work.

**Comment by manikos** [comment]
That would mean to update the PR excluding the `.mo` files? All other files stay?

**Comment by dokterbob** [comment]
Only the English po would be sufficient!
Thanks! 
-- 
Enviado a partir do meu dispositivo Android com o K-9 Mail. Peço desculpa pela brevidade.

**Comment by manikos** [comment]
Because I have deleted the related branch, I'll create a new PR. So, feel free to delete this PR. 
In the new PR I'll include the changes in the `html` files along with the `.po` files under the `en/` directory. Will that work for you?

**Pull request closed without merging**
