### PR TITLE
Django 1.8 support

### LINKED ISSUE #131: Support for Django 1.8
Few minor issues with Django 1.8:
System check issue: IPAddressField deprecated
django.contrib.admin.util deprecated for django.contrib.admin.utils
Email field now has 254 chars length

### PR DESCRIPTION
**Pull request by pcraston**
use GenericIPAddressField if available otherwise fall back to IPAddressField
fix admin.utils deprecation issue
add django 1.8 to travis tests
add migration to convert email fields to Django's new standard length

### CODE REVIEW

**Comment by pcraston** [comment]
* 1.8 build fails because django-setuptest uses django.test.simple which no longer exists in Django 1.8 (issue https://github.com/praekelt/django-setuptest/issues/23)

@dokterbob do you think it's worth waiting for django-setuptest to sort out Django 1.8 compatibility?

**Comment by pcraston** [comment]
Just an update on this, we're using our branch of django-newsletter with Django 1.8 and noticing (and fixing) issues as we go along. Will leave this PR open, hopefully eventually it'll be ready for merge.

**Comment by dokterbob** [comment]
Great, any contributions welcome! 

Let me know when you feel confident it�s stable. :)

**Comment by pcraston** [comment]
I'm not sure about the migration and making it work on different django versions. I asked on django-dev email list (https://groups.google.com/forum/#!topic/django-developers/rzK7JU-lE8Y) but not sure I'm any wiser..

**Comment by dokterbob** [comment]
@pcraston So. Tests are running on 1.8 now. Somehow passing.

Could you try and rebase your branch from master and see what it does? 

Thanks!

**Comment by pcraston** [comment]
@dokterbob All rebased. Awesome stuff! Tests passing now.

If you're happy with the way the migration is done, i.e. the ```if django.VERSION >= (1,8):``` stuff, it should be ready to merge.

**Comment by dokterbob** [comment]
Thanks for replying so quickly!

What I'm actually wondering, looking at your patch, is why the 1.8 tests were passing in the first place. See https://travis-ci.org/dokterbob/django-newsletter/jobs/70590429

**Comment by dokterbob** [comment]
Oh, wait. Deprecation issues. I understand now.

**Comment by pcraston** [comment]
@dokterbob do you think it's worth putting out a new release to pypi now that we have Django 1.8 support? (that would allow me to stop using my fork :smile: )

**Comment by dokterbob** [comment]
Yep. All it needs is a little more testing and a changelog. I hope to find time for that soon (but pull requests are always welcome!) 


Patrick Craston <notifications@github.com> schreef op 13 juli 2015 15:45:20 CEST:
>@dokterbob do you think it's worth putting out a new release to pypi
>now that we have Django 1.8 support? (that would allow me to stop using
>my fork :smile: )
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dokterbob/django-newsletter/pull/132#issuecomment-120932627

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
