### PR TITLE
Added doc info about how to use a premailer

### PR DESCRIPTION
**Pull request by Sheepzez**
Added a small section in `templates.rst` about how to use a premailer, and what options are available.

PR arises from #178.

### CODE REVIEW

**Comment by dokterbob** [comment]
Great, thanks! 

I would appreciate if you specify which 'newer' Django versions you are talking about as this documentation is likely to be around for a while. :)

**Comment by Sheepzez** [comment]
@dokterbob Noted which versions I believe the API changed in. 

If you think it's worth it, I could fork Django-Premailer and update it for newer versions (and possibly publish in Pip if you think it would be worth it). Then we could change the docs to just point to that repo/package.

**Comment by claudep** [comment]
I see no open pull requests to improve django-premailer, how can you say that it is not kept up-to-date? Maybe Alex will happily merge any proposed improvment, won't he?

**Comment by Sheepzez** [comment]
True, perhaps I'm being a little presumptuous. There's an open issue
pointing out that it's broken, and that's its been broken since 1.6, and
the last activity from the creator was a long time ago.

**Comment by claudep** [comment]
Would you have time to make the necessary pull request?

**Comment by Sheepzez** [comment]
Yep, I'll give it a go. :)

**Comment by dokterbob** [comment]
@Sheepzez Thanks for the contrib. I linked explicitly to the issue at hand, which should make it easier to know when this reference can be removed in the future and also makes it more likely someone (maybe you?) will fire a pull req. for it in the future.

**Comment by gabn88** [comment]
Thanks a lot!

**Pull request merged**
